from pycheevos.models.achievement import Achievement
from pycheevos.models.leaderboard import Leaderboard
from pycheevos.core.constants import AchievementType, LeaderboardFormat
from collections import OrderedDict

achievements = OrderedDict({
    611949: Achievement(
        id=611949,
        title="""Chaos in the Streets""",
        description="""Clear Downtown 1""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611954: Achievement(
        id=611954,
        title="""Construction Site Raid""",
        description="""Clear Downtown 2""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611955: Achievement(
        id=611955,
        title="""Feeling Llike Spiderman""",
        description="""Clear Downtown 3""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611956: Achievement(
        id=611956,
        title="""City Heights""",
        description="""Clear Downtown 4""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611957: Achievement(
        id=611957,
        title="""My Unworthy Opponent""",
        description="""Clear Downtown 5""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611958: Achievement(
        id=611958,
        title="""Entering the Sewers""",
        description="""Clear Underground 1""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611959: Achievement(
        id=611959,
        title="""The Underground Command Center""",
        description="""Clear Underground 2""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611960: Achievement(
        id=611960,
        title="""Acid Complex""",
        description="""Clear Underground 3""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611961: Achievement(
        id=611961,
        title="""Through the Railyard""",
        description="""Clear Underground 4""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611962: Achievement(
        id=611962,
        title="""Colorfully Deranged""",
        description="""Clear Underground 5""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611963: Achievement(
        id=611963,
        title="""Loading Bay Inspection""",
        description="""Clear Waterfront 1""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611964: Achievement(
        id=611964,
        title="""Under Construction!""",
        description="""Clear Waterfront 2""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611965: Achievement(
        id=611965,
        title="""Shipment Labyrinth""",
        description="""Clear Waterfront 3""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611966: Achievement(
        id=611966,
        title="""I'm the Captain Now""",
        description="""Clear Waterfront 4""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611967: Achievement(
        id=611967,
        title="""Hot Waters""",
        description="""Clear Waterfront 5""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611968: Achievement(
        id=611968,
        title="""Another Impressive Performance""",
        description="""Clear The Museum and beat the game.""",
        points=10,
        badge="00000",
        type=AchievementType.WIN_CONDITION,
    ),
    612686: Achievement(
        id=612686,
        title="""Mass Goon Extinction""",
        description="""Defeat 1500 goons""",
        points=5,
        badge="00000",
    ),
})

leaderboards = OrderedDict({
    163681: Leaderboard(
        id=163681,
        title="""Downtown 1 Time Trial""",
        description="""Clear Downtown 1 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163685: Leaderboard(
        id=163685,
        title="""Downtown 2 Time Trial""",
        description="""Clear Downtown 2 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163686: Leaderboard(
        id=163686,
        title="""Downtown 3 Time Trial""",
        description="""Clear Downtown 3 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163687: Leaderboard(
        id=163687,
        title="""Downtown 4 Time Trial""",
        description="""Clear Downtown 4 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163688: Leaderboard(
        id=163688,
        title="""Downtown 5 Time Trial""",
        description="""Clear Downtown 5 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163689: Leaderboard(
        id=163689,
        title="""Underground 1 Time Trial""",
        description="""Clear Underground 1 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163690: Leaderboard(
        id=163690,
        title="""Underground 2 Time Trial""",
        description="""Clear Underground 2 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163691: Leaderboard(
        id=163691,
        title="""Underground 3 Time Trial""",
        description="""Clear Underground 3 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163692: Leaderboard(
        id=163692,
        title="""Underground 4 Time Trial""",
        description="""Clear Underground 4 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163693: Leaderboard(
        id=163693,
        title="""Underground 5 Time Trial""",
        description="""Clear Underground 5 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163694: Leaderboard(
        id=163694,
        title="""Waterfront 1 Time Trial""",
        description="""Clear Waterfront 1 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163695: Leaderboard(
        id=163695,
        title="""Waterfront 2 Time Trial""",
        description="""Clear Waterfront 2 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163696: Leaderboard(
        id=163696,
        title="""Waterfront 3 Time Trial""",
        description="""Clear Waterfront 3 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163697: Leaderboard(
        id=163697,
        title="""Waterfront 4 Time Trial""",
        description="""Clear Waterfront 4 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163698: Leaderboard(
        id=163698,
        title="""Waterfront 5 Time Trial""",
        description="""Clear Waterfront 5 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163699: Leaderboard(
        id=163699,
        title="""Museum Time Trial""",
        description="""Clear The Museum as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163717: Leaderboard(
        id=163717,
        title="""Downtown Section Time Trial""",
        description="""Clear all Downtown levels in any order as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163718: Leaderboard(
        id=163718,
        title="""Underground Section Time Trial""",
        description="""Clear all Underground levels in any order as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163719: Leaderboard(
        id=163719,
        title="""Waterfront Section Time Trial""",
        description="""Clear all Waterfront levels in any order as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
})