from pycheevos.models.achievement import Achievement
from pycheevos.models.leaderboard import Leaderboard
from pycheevos.core.constants import AchievementType, LeaderboardFormat
from collections import OrderedDict

achievements = OrderedDict({
    611949: Achievement(
        id=611949,
        title="""Chaos in the Streets""",
        description="""Clear Downtown 1""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611954: Achievement(
        id=611954,
        title="""Construction Site Raid""",
        description="""Clear Downtown 2""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612811: Achievement(
        id=612811,
        title="""220kV of Evil Goodness""",
        description="""Unlock the Electric Lasso""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611955: Achievement(
        id=611955,
        title="""Feeling Like Spiderman""",
        description="""Clear Downtown 3""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611956: Achievement(
        id=611956,
        title="""City Heights""",
        description="""Clear Downtown 4""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611957: Achievement(
        id=611957,
        title="""My Unworthy Opponent""",
        description="""Clear Downtown 5""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611958: Achievement(
        id=611958,
        title="""Entering the Sewers""",
        description="""Clear Underground 1""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612812: Achievement(
        id=612812,
        title="""Bouncy Grenades""",
        description="""Unlock the Fusion Bouncer""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611959: Achievement(
        id=611959,
        title="""The Underground Command Center""",
        description="""Clear Underground 2""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611960: Achievement(
        id=611960,
        title="""Acid Complex""",
        description="""Clear Underground 3""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611961: Achievement(
        id=611961,
        title="""Through the Railyard""",
        description="""Clear Underground 4""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612813: Achievement(
        id=612813,
        title="""Expanding the Collection""",
        description="""Unlock the Expand-O-Matic""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611962: Achievement(
        id=611962,
        title="""Colorfully Deranged""",
        description="""Clear Underground 5""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611963: Achievement(
        id=611963,
        title="""Loading Bay Inspection""",
        description="""Clear Waterfront 1""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611964: Achievement(
        id=611964,
        title="""Under Construction!""",
        description="""Clear Waterfront 2""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    612814: Achievement(
        id=612814,
        title="""The Michael Bay Gun""",
        description="""Unlock the Doom Barrage""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611965: Achievement(
        id=611965,
        title="""Shipment Labyrinth""",
        description="""Clear Waterfront 3""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611966: Achievement(
        id=611966,
        title="""I'm the Captain Now""",
        description="""Clear Waterfront 4""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611967: Achievement(
        id=611967,
        title="""Hot Waters""",
        description="""Clear Waterfront 5""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    611968: Achievement(
        id=611968,
        title="""Another Impressive Performance""",
        description="""Clear The Museum and beat the game.""",
        points=10,
        badge="00000",
        type=AchievementType.WIN_CONDITION,
    ),
    612844: Achievement(
        id=612844,
        title="""Found These in the Trash""",
        description="""Get all MEGA collectibles in Downtown""",
        points=5,
        badge="00000",
    ),
    612845: Achievement(
        id=612845,
        title="""Sewer Rat""",
        description="""Get all MEGA collectibles in the Underground""",
        points=5,
        badge="00000",
    ),
    612846: Achievement(
        id=612846,
        title="""Illegal Cargo Seized""",
        description="""Get all MEGA collectibles at the Waterfront""",
        points=5,
        badge="00000",
    ),
    612847: Achievement(
        id=612847,
        title="""Museum Scraps""",
        description="""Get all MEGA collectibles in the Museum""",
        points=2,
        badge="00000",
    ),
    612848: Achievement(
        id=612848,
        title="""Downtown Collector""",
        description="""Get all Film Images in Downtown""",
        points=5,
        badge="00000",
    ),
    612849: Achievement(
        id=612849,
        title="""Underground Collector""",
        description="""Get all Film Images in the Underground""",
        points=5,
        badge="00000",
    ),
    612850: Achievement(
        id=612850,
        title="""Waterfront Collector""",
        description="""Get all Film Images at the Waterfront""",
        points=5,
        badge="00000",
    ),
    612851: Achievement(
        id=612851,
        title="""Museum Collector""",
        description="""Get the Film Image in the Museum""",
        points=5,
        badge="00000",
    ),
    614528: Achievement(
        id=614528,
        title="""Oooh Shiny!""",
        description="""Upgrade your first weapon""",
        points=1,
        badge="00000",
    ),
    614523: Achievement(
        id=614523,
        title="""Porter's X2 Ray Gun""",
        description="""Upgrade your Mega Blaster to its maximum level""",
        points=5,
        badge="00000",
    ),
    614524: Achievement(
        id=614524,
        title="""Supercharged Slaps""",
        description="""Upgrade your Electric Lasso to its maximum level""",
        points=5,
        badge="00000",
    ),
    614525: Achievement(
        id=614525,
        title="""Now with More Explosions""",
        description="""Upgrade your Fusion Bouncer to its maximum level""",
        points=5,
        badge="00000",
    ),
    614526: Achievement(
        id=614526,
        title="""Balloon Fan""",
        description="""Upgrade your Expand-O-Matic to its maximum level""",
        points=5,
        badge="00000",
    ),
    614527: Achievement(
        id=614527,
        title="""Even More Missiles""",
        description="""Upgrade your Doom Barrage to its maximum level""",
        points=5,
        badge="00000",
    ),
    612686: Achievement(
        id=612686,
        title="""Mass Goon Extinction""",
        description="""Defeat 1500 goons""",
        points=5,
        badge="00000",
    ),
    612842: Achievement(
        id=612842,
        title="""Untouchable""",
        description="""Complete any stage without taking damage""",
        points=5,
        badge="00000",
    ),
    614636: Achievement(
        id=614636,
        title="""The Mighty Atomic Scepter""",
        description="""Complete any stage while only using the Atomic Scepter""",
        points=5,
        badge="00000",
    ),
    614379: Achievement(
        id=614379,
        title="""Destruction Is My Job""",
        description="""Defeat Destruction Worker in Downtown without taking damage""",
        points=10,
        badge="00000",
    ),
    614380: Achievement(
        id=614380,
        title="""We Killed The Rave""",
        description="""Defeat Psycho Delic in the Underground without taking damage""",
        points=10,
        badge="00000",
    ),
    614381: Achievement(
        id=614381,
        title="""Gone in a Flash""",
        description="""Defeat Hot Flash at the Waterfront without taking damage""",
        points=10,
        badge="00000",
    ),
    614387: Achievement(
        id=614387,
        title="""Perfect City Savior""",
        description="""Defeat Tighten in The Museum without taking damage""",
        points=10,
        badge="00000",
    ),
    614637: Achievement(
        id=614637,
        title="""Sticking to My Tools""",
        description="""Defeat Tighten with only the Atomic Scepter, Mega Blaster and without using the lasso more than once""",
        points=10,
        badge="00000",
    ),
    612924: Achievement(
        id=612924,
        title="""True City Hero""",
        description="""Get all in-game achievements""",
        points=10,
        badge="00000",
    ),
    614639: Achievement(
        id=614639,
        title="""Fast Sweep in the Neighbourhood""",
        description="""Clear all Downtown levels in any order in under 28 minutes (reset by entering another section or going to the title screen)""",
        points=10,
        badge="00000",
    ),
    614640: Achievement(
        id=614640,
        title="""Funky and Fast""",
        description="""Clear all Underground levels in any order in under 40 minutes (reset by entering another section or going to the title screen)""",
        points=10,
        badge="00000",
    ),
    614641: Achievement(
        id=614641,
        title="""No Time for Fishing""",
        description="""Clear all Waterfront levels in any order in under 42 minutes (reset by entering another section or going to the title screen)""",
        points=10,
        badge="00000",
    ),
    614638: Achievement(
        id=614638,
        title="""Fast Pass""",
        description="""Clear The Museum in under 5 minutes and 30 seconds""",
        points=5,
        badge="00000",
    ),
})

leaderboards = OrderedDict({
    163681: Leaderboard(
        id=163681,
        title="""Downtown 1 Time Trial""",
        description="""Clear Downtown 1 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163685: Leaderboard(
        id=163685,
        title="""Downtown 2 Time Trial""",
        description="""Clear Downtown 2 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163686: Leaderboard(
        id=163686,
        title="""Downtown 3 Time Trial""",
        description="""Clear Downtown 3 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163687: Leaderboard(
        id=163687,
        title="""Downtown 4 Time Trial""",
        description="""Clear Downtown 4 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163688: Leaderboard(
        id=163688,
        title="""Downtown 5 Time Trial""",
        description="""Clear Downtown 5 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163689: Leaderboard(
        id=163689,
        title="""Underground 1 Time Trial""",
        description="""Clear Underground 1 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163690: Leaderboard(
        id=163690,
        title="""Underground 2 Time Trial""",
        description="""Clear Underground 2 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163691: Leaderboard(
        id=163691,
        title="""Underground 3 Time Trial""",
        description="""Clear Underground 3 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163692: Leaderboard(
        id=163692,
        title="""Underground 4 Time Trial""",
        description="""Clear Underground 4 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163693: Leaderboard(
        id=163693,
        title="""Underground 5 Time Trial""",
        description="""Clear Underground 5 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163694: Leaderboard(
        id=163694,
        title="""Waterfront 1 Time Trial""",
        description="""Clear Waterfront 1 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163695: Leaderboard(
        id=163695,
        title="""Waterfront 2 Time Trial""",
        description="""Clear Waterfront 2 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163696: Leaderboard(
        id=163696,
        title="""Waterfront 3 Time Trial""",
        description="""Clear Waterfront 3 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163697: Leaderboard(
        id=163697,
        title="""Waterfront 4 Time Trial""",
        description="""Clear Waterfront 4 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163698: Leaderboard(
        id=163698,
        title="""Waterfront 5 Time Trial""",
        description="""Clear Waterfront 5 as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163699: Leaderboard(
        id=163699,
        title="""Museum Time Trial""",
        description="""Clear The Museum as fast as possible""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163717: Leaderboard(
        id=163717,
        title="""Downtown Section Time Trial""",
        description="""Clear all Downtown levels in any order as fast as possible (reset by entering another section or going to the title screen)""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163718: Leaderboard(
        id=163718,
        title="""Underground Section Time Trial""",
        description="""Clear all Underground levels in any order as fast as possible (reset by entering another section or going to the title screen)""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    163719: Leaderboard(
        id=163719,
        title="""Waterfront Section Time Trial""",
        description="""Clear all Waterfront levels in any order as fast as possible (reset by entering another section or going to the title screen)""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
})