from pycheevos.models.achievement import Achievement
from pycheevos.models.leaderboard import Leaderboard
from pycheevos.core.constants import AchievementType, LeaderboardFormat
from collections import OrderedDict

achievements = OrderedDict({
    631253: Achievement(
        id=631253,
        title="""We've Known That We're Not Alone""",
        description="""Enter the PSS I in Adventure Mode""",
        points=1,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631263: Achievement(
        id=631263,
        title="""Not a Typo""",
        description="""Obtain the Muon Pistol in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631254: Achievement(
        id=631254,
        title="""Four Arms Were Not Enough""",
        description="""Defeat the first Guardian in the PSS I in Adventure Mode""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631255: Achievement(
        id=631255,
        title="""Taking the Buggy for a Spin""",
        description="""Successfully make your way through to PSS II in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631264: Achievement(
        id=631264,
        title="""Subatomic Particles""",
        description="""Obtain the Quanta Rifle in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631256: Achievement(
        id=631256,
        title="""Cat-and-Mouse Game""",
        description="""Defeat Sanctus Vector in the PSS II in Adventure Mode""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631257: Achievement(
        id=631257,
        title="""Close Encounters of the Third Kind""",
        description="""Fight your way through the Non-ETO Transport Vessel in Adventure Mode""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631258: Achievement(
        id=631258,
        title="""Taking out the Trash""",
        description="""Defeat the second Guardian in the Waste Disposal in Adventure Mode""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631265: Achievement(
        id=631265,
        title="""Otherworldly Sniper""",
        description="""Obtain the Fermion Sniper in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631259: Achievement(
        id=631259,
        title="""Releasing the Adrenalin""",
        description="""Defeat the Phexic Manifold in the Power Station in Adventure Mode""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631266: Achievement(
        id=631266,
        title="""Bug Spray""",
        description="""Obtain the Lepton Spread in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631260: Achievement(
        id=631260,
        title="""Bad Things Come in Threes""",
        description="""Defeat the third and final Guardian in the Cold Process in Adventure Mode""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631267: Achievement(
        id=631267,
        title="""Not a Rocket Launcher""",
        description="""Obtain the Oxid Cannon in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631268: Achievement(
        id=631268,
        title="""Not a Bigger Rocket Launcher""",
        description="""Obtain the Seeker Pod in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631261: Achievement(
        id=631261,
        title="""Deeper in Hell""",
        description="""Defeat the Matrix Progenitor in the Irradiated Stratum in Adventure Mode""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631262: Achievement(
        id=631262,
        title="""It's Just the Beginning""",
        description="""Defeat the Overlord and beat the game in Adventure Mode""",
        points=10,
        badge="00000",
        type=AchievementType.WIN_CONDITION,
    ),
    631407: Achievement(
        id=631407,
        title="""Really Wanted to Get out of Here""",
        description="""Defeat the first Guardian in under 1 minute in Normal in Quick Play""",
        points=5,
        badge="00000",
    ),
    633132: Achievement(
        id=633132,
        title="""Won't Be There for the Fireworks""",
        description="""Exit the PSS I with at least 35 seconds remaining""",
        points=5,
        badge="00000",
    ),
    631469: Achievement(
        id=631469,
        title="""Come Back Here!""",
        description="""Defeat the Sanctus Vector without letting it recover health for more than 15 seconds in Normal in Quick Play""",
        points=10,
        badge="00000",
    ),
    633133: Achievement(
        id=633133,
        title="""Low Ping""",
        description="""Reach the last satellite with at least 60 seconds remaining""",
        points=5,
        badge="00000",
    ),
    631408: Achievement(
        id=631408,
        title="""Not Flying Off Just Yet""",
        description="""Complete the Non-ETO Transport Vessel section and defeat the Core in under 2 minutes and 30 seconds in Normal in Quick Play""",
        points=5,
        badge="00000",
    ),
    631409: Achievement(
        id=631409,
        title="""Merry-Go-Round""",
        description="""Defeat the second Guardian in under 1 minute and 15 seconds in Normal in Quick Play""",
        points=10,
        badge="00000",
    ),
    633036: Achievement(
        id=633036,
        title="""Day at the Range""",
        description="""Defeat the Phexic Manifold with at least 95% accuracy in Normal in Quick Play""",
        points=10,
        badge="00000",
    ),
    631410: Achievement(
        id=631410,
        title="""Stone Cold""",
        description="""Defeat the third Guardian in under 2 minutes in Normal in Quick Play""",
        points=25,
        badge="00000",
    ),
    633027: Achievement(
        id=633027,
        title="""End Log""",
        description="""Defeat the Overlord in under 3 minutes in Normal in Quick Play""",
        points=10,
        badge="00000",
    ),
    633028: Achievement(
        id=633028,
        title="""Experimental Procedures""",
        description="""Complete the PSS I section and defeat the first Guardian in Veteran in Adventure Mode""",
        points=5,
        badge="00000",
    ),
    633029: Achievement(
        id=633029,
        title="""Initial Processing""",
        description="""Complete the PSS II section and defeat the Sanctus Vector in Veteran in Adventure Mode""",
        points=10,
        badge="00000",
    ),
    633030: Achievement(
        id=633030,
        title="""Rushing to the Core""",
        description="""Complete the Non-ETO Transport Vessel section and defeat the Core in Veteran in Adventure Mode""",
        points=5,
        badge="00000",
    ),
    633031: Achievement(
        id=633031,
        title="""Freedom 2 Survivor""",
        description="""Complete the Waste Disposal section and defeat the second Guardian in Veteran in Adventure Mode""",
        points=10,
        badge="00000",
    ),
    633032: Achievement(
        id=633032,
        title="""Brutes Extermination Protocol""",
        description="""Complete the Power Station section and defeat the Phexic Manifold in Veteran in Adventure Mode""",
        points=10,
        badge="00000",
    ),
    633033: Achievement(
        id=633033,
        title="""Freezer Burn""",
        description="""Complete the Cold Process section and defeat the third Guardian in Veteran in Adventure Mode""",
        points=25,
        badge="00000",
    ),
    633034: Achievement(
        id=633034,
        title="""Radioactive""",
        description="""Complete the Irradiated Stratum section and defeat the Matrix Progenitor in Veteran in Adventure Mode""",
        points=10,
        badge="00000",
    ),
    633035: Achievement(
        id=633035,
        title="""Fly Me to the Moon""",
        description="""Complete the Fermian Homeworld section and defeat the Sector Overlord in Veteran in Adventure Mode""",
        points=25,
        badge="00000",
    ),
})

leaderboards = OrderedDict({
    170216: Leaderboard(
        id=170216,
        title="""Timer Display""",
        description="""Hold L+R+Select for 5 seconds to display the timer. Warning : timer displayed by the game on the end screen is incorrect!""",
        format=LeaderboardFormat.TIME,
        lower_is_better=False,
    ),
    169465: Leaderboard(
        id=169465,
        title="""Guardian I Normal Time Trial""",
        description="""Defeat the first Guardian as fast as possible in Normal""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169466: Leaderboard(
        id=169466,
        title="""Guardian I Veteran Time Trial""",
        description="""Defeat the first Guardian as fast as possible in Veteran""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169467: Leaderboard(
        id=169467,
        title="""Sanctus Vector Normal Time Trial""",
        description="""Defeat the Sanctus Vector as fast as possible in Normal""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169468: Leaderboard(
        id=169468,
        title="""Sanctus Vector Veteran Time Trial""",
        description="""Defeat the Sanctus Vector as fast as possible in Veteran""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169469: Leaderboard(
        id=169469,
        title="""Core Normal Time Trial""",
        description="""Destroy the Core in the Non-ETEO Transport Vessel as fast as possible in Normal""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169470: Leaderboard(
        id=169470,
        title="""Core Veteran Time Trial""",
        description="""Destroy the Core in the Non-ETEO Transport Vessel as fast as possible in Veteran""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169471: Leaderboard(
        id=169471,
        title="""Guardian II Time Trial""",
        description="""Defeat the second Guardian as fast as possible in Normal""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169472: Leaderboard(
        id=169472,
        title="""Guardian II Veteran Time Trial""",
        description="""Defeat the second Guardian as fast as possible in Veteran""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169473: Leaderboard(
        id=169473,
        title="""Phexic Manifold Normal Time Trial""",
        description="""Defeat the Phexic Manifold as fast as possible in Normal""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169474: Leaderboard(
        id=169474,
        title="""Phexic Manifold Veteran Time Trial""",
        description="""Defeat the Phexic Manifold as fast as possible in Veteran""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169475: Leaderboard(
        id=169475,
        title="""Guardian III Normal Time Trial""",
        description="""Defeat the third Guardian as fast as possible in Normal""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169476: Leaderboard(
        id=169476,
        title="""Guardian III Veteran Time Trial""",
        description="""Defeat the third Guardian as fast as possible in Veteran""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169477: Leaderboard(
        id=169477,
        title="""Matrix Progenitor Normal Time Trial""",
        description="""Defeat the Matrix Progenitor as fast as possible in Normal""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169478: Leaderboard(
        id=169478,
        title="""Matrix Progenitor Veteran Time Trial""",
        description="""Defeat the Matrix Progenitor as fast as possible in Veteran""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169479: Leaderboard(
        id=169479,
        title="""Overlord Normal Time Trial""",
        description="""Defeat the Overlord as fast as possible in Normal""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    169480: Leaderboard(
        id=169480,
        title="""Overlord Veteran Time Trial""",
        description="""Defeat the Overlord as fast as possible in Veteran""",
        format=LeaderboardFormat.TIME,
        lower_is_better=True,
    ),
    170264: Leaderboard(
        id=170264,
        title="""PSS I Escape Time Trial""",
        description="""Reach the exit of the PSS I as fast as possible""",
        format=LeaderboardFormat.SECS,
        lower_is_better=False,
    ),
    170265: Leaderboard(
        id=170265,
        title="""Satellite Time Trial""",
        description="""Reach the satellite after exiting the PSS II as fast as possible""",
        format=LeaderboardFormat.SECS,
        lower_is_better=False,
    ),
})