from pycheevos.models.achievement import Achievement
from pycheevos.models.leaderboard import Leaderboard
from pycheevos.core.constants import AchievementType, LeaderboardFormat
from collections import OrderedDict

achievements = OrderedDict({
    631253: Achievement(
        id=631253,
        title="""This Is Just the Beginning""",
        description="""Enter the PSS I in Adventure Mode""",
        points=1,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631263: Achievement(
        id=631263,
        title="""Not a Typo""",
        description="""Obtain the Muon Pistol in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631254: Achievement(
        id=631254,
        title="""Four Arms Were Not Enough""",
        description="""Defeat the first Guardian in the PSS I in Adventure Mode""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631255: Achievement(
        id=631255,
        title="""Taking the Buggy for a Spin""",
        description="""Successfully make your way through to PSS II in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631264: Achievement(
        id=631264,
        title="""Subatomic Particles""",
        description="""Obtain the Quanta Rifle in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631256: Achievement(
        id=631256,
        title="""Cat-and-Mouse Game""",
        description="""Defeat Sanctus Vector in the PSS II in Adventure Mode""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631257: Achievement(
        id=631257,
        title="""Close Encounters of the Third Kind""",
        description="""Fight your way through the Non-ETO Transport Vessel in Adventure Mode""",
        points=3,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631258: Achievement(
        id=631258,
        title="""Taking Out the Trash""",
        description="""Defeat the second Guardian in the Waste Disposal in Adventure Mode""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631265: Achievement(
        id=631265,
        title="""Otherworldly Sniper""",
        description="""Obtain the Fermion Sniper in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631259: Achievement(
        id=631259,
        title="""Releasing the Adrenalin""",
        description="""Defeat the Phexic Manifold in the Power Station in Adventure Mode""",
        points=5,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631266: Achievement(
        id=631266,
        title="""Bug Spray""",
        description="""Obtain the Lepton Spread in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631260: Achievement(
        id=631260,
        title="""Bad Things Come in Threes""",
        description="""Defeat the third and final Guardian in the Cold Process in Adventure Mode""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631267: Achievement(
        id=631267,
        title="""Not a Rocket Launcher""",
        description="""Obtain the Oxid Cannon in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631268: Achievement(
        id=631268,
        title="""Not a Bigger Rocket Launcher""",
        description="""Obtain the Seeker Pod in Adventure Mode""",
        points=2,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631261: Achievement(
        id=631261,
        title="""Deeper in Hell""",
        description="""Defeat the Matrix Progenitor in the Irradiated Stratum in Adventure Mode""",
        points=10,
        badge="00000",
        type=AchievementType.PROGRESSION,
    ),
    631262: Achievement(
        id=631262,
        title="""Fly Me to the Moon""",
        description="""Defeat the Overlord and beat the game in Adventure Mode""",
        points=25,
        badge="00000",
        type=AchievementType.WIN_CONDITION,
    ),
})

leaderboards = OrderedDict({
})