from pycheevos.models.achievement import Achievement
from pycheevos.models.leaderboard import Leaderboard
from pycheevos.core.constants import AchievementType, LeaderboardFormat
from collections import OrderedDict

achievements = OrderedDict({
    631253: Achievement(
        id=631253,
        title="""We've Known That We're Not Alone""",
        description="""Enter the PSS I""",
        points=1,
        badge="726531",
        type=AchievementType.PROGRESSION,
    ),
    631263: Achievement(
        id=631263,
        title="""Not a Typo""",
        description="""Obtain the Muon Pistol""",
        points=2,
        badge="726532",
    ),
    631254: Achievement(
        id=631254,
        title="""Four Arms Were Not Enough""",
        description="""Defeat the first Guardian in the PSS I""",
        points=5,
        badge="726533",
        type=AchievementType.PROGRESSION,
    ),
    631255: Achievement(
        id=631255,
        title="""Taking the Buggy for a Spin""",
        description="""Make your way through to PSS II""",
        points=2,
        badge="726534",
        type=AchievementType.PROGRESSION,
    ),
    631264: Achievement(
        id=631264,
        title="""Subatomic Particles""",
        description="""Obtain the Quanta Rifle""",
        points=2,
        badge="726535",
    ),
    631256: Achievement(
        id=631256,
        title="""Cat-and-Mouse Game""",
        description="""Defeat the Sanctus Vector in the PSS II""",
        points=10,
        badge="726536",
        type=AchievementType.PROGRESSION,
    ),
    631257: Achievement(
        id=631257,
        title="""Close Encounters of the Third Kind""",
        description="""Fight your way through the Non-ETO Transport Vessel""",
        points=5,
        badge="726537",
        type=AchievementType.PROGRESSION,
    ),
    631258: Achievement(
        id=631258,
        title="""Taking Out the Trash""",
        description="""Defeat the second Guardian in the Waste Disposal""",
        points=5,
        badge="726538",
        type=AchievementType.PROGRESSION,
    ),
    631265: Achievement(
        id=631265,
        title="""Otherworldly Sniper""",
        description="""Obtain the Fermion Sniper""",
        points=2,
        badge="726539",
        type=AchievementType.MISSABLE,
    ),
    631259: Achievement(
        id=631259,
        title="""Releasing the Adrenaline""",
        description="""Defeat the Phexic Manifold in the Power Station""",
        points=5,
        badge="726540",
        type=AchievementType.PROGRESSION,
    ),
    631266: Achievement(
        id=631266,
        title="""Bug Spray""",
        description="""Obtain the Lepton Spread""",
        points=2,
        badge="726541",
        type=AchievementType.MISSABLE,
    ),
    631260: Achievement(
        id=631260,
        title="""Bad Things Come In Threes""",
        description="""Defeat the third and final Guardian in the Cold Process""",
        points=10,
        badge="726542",
        type=AchievementType.PROGRESSION,
    ),
    631267: Achievement(
        id=631267,
        title="""Not a Rocket Launcher""",
        description="""Obtain the Oxid Cannon""",
        points=2,
        badge="726543",
        type=AchievementType.MISSABLE,
    ),
    631268: Achievement(
        id=631268,
        title="""Not a Bigger Rocket Launcher""",
        description="""Obtain the Seeker Pod""",
        points=2,
        badge="726544",
        type=AchievementType.MISSABLE,
    ),
    631261: Achievement(
        id=631261,
        title="""Deeper in Hell""",
        description="""Defeat the Matrix Progenitor in the Irradiated Stratum""",
        points=10,
        badge="726545",
        type=AchievementType.PROGRESSION,
    ),
    631262: Achievement(
        id=631262,
        title="""It's Just the Beginning""",
        description="""Defeat the Overlord and beat the game""",
        points=10,
        badge="726546",
        type=AchievementType.WIN_CONDITION,
    ),
    633330: Achievement(
        id=633330,
        title="""Can Take a Punch""",
        description="""Find every health increase in Adventure Mode""",
        points=5,
        badge="726547",
        type=AchievementType.MISSABLE,
    ),
    633331: Achievement(
        id=633331,
        title="""Stocked Up""",
        description="""Find every ammo clip increase in Adventure Mode""",
        points=5,
        badge="726548",
        type=AchievementType.MISSABLE,
    ),
    633751: Achievement(
        id=633751,
        title="""Alienated Wisdom""",
        description="""Collect every Alien Artifacts and complete Episode 01""",
        points=5,
        badge="726549",
    ),
    633752: Achievement(
        id=633752,
        title="""A Heightened Outlook""",
        description="""Collect every Alien Artifacts and complete Episode 04""",
        points=5,
        badge="726550",
    ),
    633753: Achievement(
        id=633753,
        title="""An Artifactual Gift""",
        description="""Collect every Alien Artifacts and complete Episode 08""",
        points=5,
        badge="726551",
    ),
    633754: Achievement(
        id=633754,
        title="""Don't Fear What We Can't Understand""",
        description="""Collect every Alien Artifacts and complete Episode 10""",
        points=5,
        badge="726552",
    ),
    633755: Achievement(
        id=633755,
        title="""What's Alien Should Be Analyzed""",
        description="""Collect every Alien Artifacts and complete Episode 12""",
        points=5,
        badge="726553",
    ),
    633756: Achievement(
        id=633756,
        title="""To Brave the Great Unknown...""",
        description="""Collect every Alien Artifacts and complete Episode 14""",
        points=5,
        badge="726554",
    ),
    633757: Achievement(
        id=633757,
        title="""A Little Extra Credit""",
        description="""Earn every Extra Merit and complete Episode 01""",
        points=5,
        badge="726555",
    ),
    633758: Achievement(
        id=633758,
        title="""The Moon and Us Know No Bounds""",
        description="""Earn every Extra Merit and complete Episode 04""",
        points=5,
        badge="726556",
    ),
    633759: Achievement(
        id=633759,
        title="""No Such Thing as Going Too Far""",
        description="""Earn every Extra Merit and complete Episode 08""",
        points=5,
        badge="726557",
    ),
    633760: Achievement(
        id=633760,
        title="""Don't Let Orbit Restrict You""",
        description="""Earn every Extra Merit and complete Episode 10""",
        points=5,
        badge="726558",
    ),
    633761: Achievement(
        id=633761,
        title="""Learning a Harsh Truth""",
        description="""Earn every Extra Merit and complete Episode 12""",
        points=5,
        badge="726559",
    ),
    633762: Achievement(
        id=633762,
        title="""It's Human Nature to Go the Extra Mile""",
        description="""Earn every Extra Merit and complete Episode 14""",
        points=5,
        badge="726560",
    ),
    633421: Achievement(
        id=633421,
        title="""Tsukigami's VR Training""",
        description="""Complete every VR Training Mission""",
        points=5,
        badge="726561",
    ),
    633422: Achievement(
        id=633422,
        title="""Tsukigami's VeteRan Training""",
        description="""Complete every VR Training Mission on Veteran difficulty""",
        points=10,
        badge="726562",
    ),
    631407: Achievement(
        id=631407,
        title="""Really Wanted to Get Out of Here...""",
        description="""Defeat the first Guardian in less than 1:00 in Quick Play Mode on Normal difficulty""",
        points=5,
        badge="726563",
    ),
    633132: Achievement(
        id=633132,
        title="""Won't Be There for the Fireworks""",
        description="""Exit PSS I with at least 35 seconds remaining""",
        points=5,
        badge="726564",
    ),
    631469: Achievement(
        id=631469,
        title="""Come Back Here!""",
        description="""Defeat the Sanctus Vector without letting it regenerate for more than 10 seconds in Quick Play Mode on Normal difficulty""",
        points=10,
        badge="726565",
    ),
    633133: Achievement(
        id=633133,
        title="""Low Ping""",
        description="""Reach the last satellite with at least 60 seconds remaining""",
        points=5,
        badge="726566",
    ),
    631408: Achievement(
        id=631408,
        title="""Not Flying Off Just Yet""",
        description="""Defeat the Core in less than 2:30 in Quick Play Mode on Normal difficulty""",
        points=5,
        badge="726567",
    ),
    631409: Achievement(
        id=631409,
        title="""Merry-Go-Round""",
        description="""Defeat the second Guardian in less than 1:15 in Quick Play Mode on Normal difficulty""",
        points=10,
        badge="726568",
    ),
    633036: Achievement(
        id=633036,
        title="""Day at the Range""",
        description="""Defeat the Phexic Manifold with at least 95% accuracy in Quick Play Mode on Normal difficulty""",
        points=10,
        badge="726569",
    ),
    631410: Achievement(
        id=631410,
        title="""Stone Cold""",
        description="""Defeat the third Guardian in less than 2:00 in Quick Play Mode on Normal difficulty""",
        points=25,
        badge="726570",
    ),
    633763: Achievement(
        id=633763,
        title="""Sniper Blaster""",
        description="""Defeat the Matrix Progenitor using only the Fermion Sniper and the Oxid Cannon in Quick Play Mode on Normal difficulty""",
        points=5,
        badge="726571",
    ),
    633027: Achievement(
        id=633027,
        title="""End Log""",
        description="""Defeat the Overlord in less than 3:00 in Quick Play Mode on Normal difficulty""",
        points=10,
        badge="726572",
    ),
    633028: Achievement(
        id=633028,
        title="""Experimental Procedures""",
        description="""Defeat the first Guardian in Adventure Mode on Veteran difficulty""",
        points=5,
        badge="726573",
    ),
    633029: Achievement(
        id=633029,
        title="""Initial Processing""",
        description="""Defeat the Sanctus Vector in Adventure Mode on Veteran difficulty""",
        points=10,
        badge="726574",
    ),
    633030: Achievement(
        id=633030,
        title="""Rushing to the Core""",
        description="""Defeat the Core in Adventure Mode on Veteran difficulty""",
        points=5,
        badge="726575",
    ),
    633031: Achievement(
        id=633031,
        title="""Freedom 2 Survivor""",
        description="""Defeat the second Guardian in Adventure Mode on Veteran difficulty""",
        points=10,
        badge="726576",
    ),
    633032: Achievement(
        id=633032,
        title="""Brutes Extermination Protocol""",
        description="""Defeat the Phexic Manifold in Adventure Mode on Veteran difficulty""",
        points=10,
        badge="726577",
    ),
    633033: Achievement(
        id=633033,
        title="""Freezer Burn""",
        description="""Defeat the third Guardian in Adventure Mode on Veteran difficulty""",
        points=25,
        badge="726578",
    ),
    633034: Achievement(
        id=633034,
        title="""Radioactive""",
        description="""Defeat the Matrix Progenitor in Adventure Mode on Veteran difficulty""",
        points=10,
        badge="726579",
    ),
    633035: Achievement(
        id=633035,
        title="""Fly Me to the Moon""",
        description="""Defeat the Sector Overlord in Adventure Mode on Veteran difficulty""",
        points=25,
        badge="726580",
    ),
})

leaderboards = OrderedDict({
    170216: Leaderboard(
        id=170216,
        title="""Timer Display""",
        description="""Hold L+R+Select for 5 seconds to display the timer. Warning : timer displayed by the game on the end screen is incorrect!""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=False,
    ),
    169465: Leaderboard(
        id=169465,
        title="""Guardian I Normal Time Trial""",
        description="""Defeat the first Guardian as fast as possible in Normal""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169466: Leaderboard(
        id=169466,
        title="""Guardian I Veteran Time Trial""",
        description="""Defeat the first Guardian as fast as possible in Veteran""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169467: Leaderboard(
        id=169467,
        title="""Sanctus Vector Normal Time Trial""",
        description="""Defeat the Sanctus Vector as fast as possible in Normal""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169468: Leaderboard(
        id=169468,
        title="""Sanctus Vector Veteran Time Trial""",
        description="""Defeat the Sanctus Vector as fast as possible in Veteran""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169469: Leaderboard(
        id=169469,
        title="""Core Normal Time Trial""",
        description="""Destroy the Core in the Non-ETEO Transport Vessel as fast as possible in Normal""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169470: Leaderboard(
        id=169470,
        title="""Core Veteran Time Trial""",
        description="""Destroy the Core in the Non-ETEO Transport Vessel as fast as possible in Veteran""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169471: Leaderboard(
        id=169471,
        title="""Guardian II Normal Time Trial""",
        description="""Defeat the second Guardian as fast as possible in Normal""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169472: Leaderboard(
        id=169472,
        title="""Guardian II Veteran Time Trial""",
        description="""Defeat the second Guardian as fast as possible in Veteran""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169473: Leaderboard(
        id=169473,
        title="""Phexic Manifold Normal Time Trial""",
        description="""Defeat the Phexic Manifold as fast as possible in Normal""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169474: Leaderboard(
        id=169474,
        title="""Phexic Manifold Veteran Time Trial""",
        description="""Defeat the Phexic Manifold as fast as possible in Veteran""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169475: Leaderboard(
        id=169475,
        title="""Guardian III Normal Time Trial""",
        description="""Defeat the third Guardian as fast as possible in Normal""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169476: Leaderboard(
        id=169476,
        title="""Guardian III Veteran Time Trial""",
        description="""Defeat the third Guardian as fast as possible in Veteran""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169477: Leaderboard(
        id=169477,
        title="""Matrix Progenitor Normal Time Trial""",
        description="""Defeat the Matrix Progenitor as fast as possible in Normal""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169478: Leaderboard(
        id=169478,
        title="""Matrix Progenitor Veteran Time Trial""",
        description="""Defeat the Matrix Progenitor as fast as possible in Veteran""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169479: Leaderboard(
        id=169479,
        title="""Overlord Normal Time Trial""",
        description="""Defeat the Overlord as fast as possible in Normal""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    169480: Leaderboard(
        id=169480,
        title="""Overlord Veteran Time Trial""",
        description="""Defeat the Overlord as fast as possible in Veteran""",
        format=LeaderboardFormat.FRAMES,
        lower_is_better=True,
    ),
    170264: Leaderboard(
        id=170264,
        title="""PSS I Escape Time Trial""",
        description="""Reach the exit of the PSS I as fast as possible""",
        format=LeaderboardFormat.TIMESECS,
        lower_is_better=False,
    ),
    170265: Leaderboard(
        id=170265,
        title="""Satellite Time Trial""",
        description="""Reach the satellite after exiting the PSS II as fast as possible""",
        format=LeaderboardFormat.TIMESECS,
        lower_is_better=False,
    ),
})